
path: /Users/91760/Football_analysis/Computer_Vision_learnings/Object Detection/prepare_data/data  # dataset root dir
train: train/images  # train images (relative to 'path')
val: validation/images  # val images (relative to 'path')

# Classes
names:
  0: alpaca