
path: /path/to/data  # dataset root dir
train: /path/to/train/images  # train images (relative to 'path')
val: /path/to/validation/images   # val images (relative to 'path')

# Classes
names:
  0: alpaca
